### ISSUE TITLE
The situation with parameters after the url will be invalid. Can you handle it? thanks（url后面带参数的情况会失效，可以处理下吗？）

### ISSUE THREAD

**Issue by ctq123** [zpao/qrcode.react#100]
for example
```js
// the normal demo 
var React = require('react');
var QRCode = require('qrcode.react');
 
React.render(
  <QRCode value="http://facebook.github.io/react" />,
  mountNode
)
```

```js
// this is invalid demo
var React = require('react');
var QRCode = require('qrcode.react');
 
React.render(
  <QRCode value="http://facebook.github.io/react?id=123" />,
  mountNode
)
```
The case with parameters after the url will be invalid. And I hope it will be fixed. thank you
(对于后面带参数的情况可以处理下吗？目前是失效的)

**Comment by ctq123** [comment]
the invalid demo can generate the qrcode image. but it can not be scaned and visited.

**Comment by zpao** [comment]
This works fine in every qrcode scanning app I tested with (iOS camera, iOS Firefox, 2 other qrcode readers). Do you have another example?

**Comment by ctq123** [comment]
Oh, I finally knew where the problem was because I set up the imageSettings.

```js
// this is invalid demo
var React = require("react"');
var QRCode = require("qrcode.react");

<QRCode
            id={"qrcode-canvas"}
            value={"http://facebook.github.io/react?id=123"}
            imageSettings={{
              src: "http://{your logo image}",
              width: 24,
              height: 24,
              excavate: true,
            }}
          />
```

```js
// this demo works fine
var React = require("react"');
var QRCode = require("qrcode.react");

<QRCode
            id={"qrcode-canvas"}
            value={"http://facebook.github.io/react?id=123"}
          />
```


thanks a lot

**Comment by zpao** [comment]
There's an inherent risk to using an image in the QR Code. Specifically the risk is that it takes away too much of the actual scannable portion. By excavating (as seems to be the difference in your demos) you're actually taking away even more modules, not just the ones that are getting covered by the image. I don't have any protections in there to prevent embedding an image that covers up more than the error correction level can handle (the math got messy, transparent images change the math) so if you find yourself with a QR Code that doesn't scan, you need to correct that yourself. You have 2 options:

1. Change the ratio of QR Code to image size. Make the image smaller or the QR Code bigger.
2. Increase the Error level (`level`), which will result in smaller modules with a better ability to handle covered areas.
