### ISSUE TITLE
Couldn't get lib folder

### ISSUE THREAD

**Issue by iamdevelopergirl** [zpao/qrcode.react#101]
While trying to install the qrcode, lib folder is not getting created. It says : "npm WARN lifecycle qrcode.react@0.9.3~prepublish: cannot run in wd qrcode.react@0.9.3 flow && make clean && make all". Is there any specific requirements for this package to be installed?

**Comment by zpao** [comment]
It looks like you're `git clone`ing and trying to build. If you're not working on this library, then I'd recommend installing using `npm` (or `yarn` if that's your jam). Does that help? If you are trying to work on this library I can help more.

**Comment by iamdevelopergirl** [comment]
npm installing of this library is working properly. I am trying to just clone this project and do a browserify of the library, so that i can use it in the extension i am working. But the qrcode source file that i need to get from lib folder is not getting generated when i do so.

**Comment by zpao** [comment]
You should probably be browserifying the npm version since it's already built.

If you want to build locally clone, run yarn and run make.
