### ISSUE TITLE
Add logo image to SVG + download?

### ISSUE THREAD

**Issue by MovingGifts** [zpao/qrcode.react#105]
Hi, is there any way to add a logo to the center of the svg qr code and be able to download it as part of the code where it is nice and crisp?

I can't find a way to download the qr code with a logo image in the center when using svg, which is needed for print quality. It seems `qrcode.react` does not include the image itself directly into the QR code (it uses a link), that is why you cannot download it.

Any ideas?

**Comment by MovingGifts** [comment]
@zpao Any idea how to merge the svg logo with the svg qr code and download them merged as a single svg?

**Comment by zpao** [comment]
I think downloading the image in JS and base64 encoding it inline would work. I don't have any intention of doing that but if somebody wanted to, I'd consider it. Downloading is not the primary use case I intend to support.

**Comment by kirtishjain9** [comment]
Hi,

Did someone find the exact solution for this? 

How should I download the QR Code with a logo image in center when using renderAs = 'svg'?

```
<QRCode
          renderAs={"svg"}
          value={card}
          size={300}
          fgColor={"#1A4074"}
          imageSettings={imageObject}
          level={"H"}
        />
```

QR code with logo at center is being displayed correctly in HTML page but when I download it using "triggerBase64Download" method from "react-base64-downloader" React library to download and save it as image, QR Code doesn't showing the logo image at the center.

Any help would be appreciated.

**Comment by Alex-Anev** [comment]
> Hi,
> 
> Did someone find the exact solution for this?
> 
> How should I download the QR Code with a logo image in center when using renderAs = 'svg'?
> 
> ```
> <QRCode
>           renderAs={"svg"}
>           value={card}
>           size={300}
>           fgColor={"#1A4074"}
>           imageSettings={imageObject}
>           level={"H"}
>         />
> ```
> 
> QR code with logo at center is being displayed correctly in HTML page but when I download it using "triggerBase64Download" method from "react-base64-downloader" React library to download and save it as image, QR Code doesn't showing the logo image at the center.
> 
> Any help would be appreciated.

I used 'react-component-export-image'. There's a whole process with useRef and whatever else to implement it. Lets me download whatever component I give it as a png and some other formats. Good luck

**Comment by Alex-Anev** [comment]
> Hi,
> 
> Did someone find the exact solution for this?
> 
> How should I download the QR Code with a logo image in center when using renderAs = 'svg'?
> 
> ```
> <QRCode
>           renderAs={"svg"}
>           value={card}
>           size={300}
>           fgColor={"#1A4074"}
>           imageSettings={imageObject}
>           level={"H"}
>         />
> ```
> 
> QR code with logo at center is being displayed correctly in HTML page but when I download it using "triggerBase64Download" method from "react-base64-downloader" React library to download and save it as image, QR Code doesn't showing the logo image at the center.
> 
> Any help would be appreciated.

I fixed it for real this time.

In my case I'm using 'react-component-export-image' for image downloads. You make a div which you reference to the 

```
const QRGenerator = React.forwardRef((props, ref) => (
  <div 
    ref={ref} /** the ref is used to grab the whole div and pass it and everything inside into a PNG converter and downloader function */
    style={{
      width: props.size,
      height: props.size,
      position: "relative"
  }}>
    <QRCode
      value={'www.google.com'}
      renderAs={'svg'}
      size={props.size}
      imageSettings={{
        excavate: true,
        height: props.size / 2.5,
        width: props.size / 2.5
      }}
    />
  /** manually put the logo on the page and place it in the middle with css */
    <img src={logo} style={{
      position: "absolute",
      transform: "translate(-50%,-50%)",
      top: "50%",
      left: "50%",
      height: props.size / 2.5,
      width: props.size / 2.5
    }} />
  </div >
))
```
Basically excavate a clear place for the image to be 'pasted' into. Remember to pass the size from props if you're doing any resizing. Hope this helps.

**Comment by PoryaKhazaee** [comment]
You can use this code sample
`import React from "react`;
`import QRCode from "qrcode.react";`
`class Component extends React.Component {
    constructor(props) {
        super(props);
        this.download = this.download.bind(this);
    };

    download() {
        const canvas: any = document.querySelector('.HpQrcode > canvas');
        const link = document.createElement("a");
        link.href = canvas.toDataURL();
        link.download = "imgName" + "-QR.png";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    };  

    render() {
        return (
             <div>
		<div className="HpQrcode d-flex align-items-center justify-content-center my-2 position-relative">
                     <QRCode 
                          value="http://awesome.link.qr"
                          id="QRCode-svg"
                          size={150} 
                      />
                </div> 
            	<button 
                      className="btn-success border-0 rounded w-50 py-2 text-center my-2 d-flex align-items-center justify-content-center align-self-center"
                      onClick={this.download}
                >
                     download
                 </button>    
             </div>
        );
    };
};
export default Component;`

**Comment by puttimeth** [comment]
Just want to share my code in case someone want more reference. This answer only download part of the question. For the logo image, I didn't implement it. This code add white padding to the download image for easier scan so it might look different.

```js
// download function
const downloadQrCode = () => {
  const svgElement = document.querySelector("#qr-code");
  if (!svgElement) return;
  // convert svg to image
  const img = new Image();
  const svgStr = new XMLSerializer().serializeToString(svgElement);
  img.src = "data:image/svg+xml;base64," + window.btoa(svgStr);
  img.onload = () => {
    // write image to canvas
    const canvas = document.createElement("canvas");
    // size of the image
    const size = 500;
    // padding for easier scan
    const padding = 20;
    canvas.width = size;
    canvas.height = size;
    const ctx = canvas.getContext("2d");
    // color of the padding
    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, size, size);
    ctx.drawImage(img, padding, padding, size - padding * 2, size - padding * 2);
    // add canvas to <a>
    const link = document.createElement("a");
    link.href = canvas.toDataURL("image/png");
    link.download = "QR code.png";
    // add to body, click to download and remove it from body
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };
};

// render component
// show qr code
<QRCodeSVG id="qr-code" size={500} value={qrCode} />
// show download button
<button onClick={downloadQrCode}>
  Download
</button>

**Comment by zpao** [comment]
I just shipped v4 and there's an example showing how to do this: https://zpao.github.io/qrcode.react/?demo=download

**Comment by sdraper69** [comment]
Can I suggest making the code a bit easy to read/access on your example?
