### ISSUE TITLE
Warning: React does not recognize the `imageSettings` prop on a DOM element.

### ISSUE THREAD

**Issue by ccaa7530** [zpao/qrcode.react#109]
qrcode.react version : 0.9.3

<img width="844" alt="截圖 2020-04-22 上午9 59 28" src="https://user-images.githubusercontent.com/23519638/79932564-61389580-8480-11ea-9691-4748b9e9d335.png">

<img width="392" alt="截圖 2020-04-22 上午10 04 46" src="https://user-images.githubusercontent.com/23519638/79932708-b5437a00-8480-11ea-9c9c-f831af7c2a8c.png">

**Comment by zpao** [comment]
This was fixed in v1.0.0. I'm not likely to backport and ship another v0.9.x.
