### ISSUE TITLE
SVG generated with `shapeRendering` attribute instead of `shape-rendering`

### ISSUE THREAD

**Issue by kopijunkie** [zpao/qrcode.react#113]
Hi there,

We're using the library in our product and it was pointed out to us that the SVG rendered does not pass W3C validation due to the SVG having `shapeRendering` attribute instead of `shape-rendering`. I've raised a PR [#112](https://github.com/zpao/qrcode.react/pull/112) to address this but if you have any thoughts on this do let me know if we might have missed something.

Our code for the QR code generation is quite simple, just 
`<QRCode renderAs="svg" size={size} level={level} value={url} />`

**Comment by zpao** [comment]
React should convert `shapeRendering` to `shape-rendering` when creating the DOM nodes (and when rendering to string). Is there a specific usage where you aren't seeing that? It could perhaps be an issue of outdated React install.

**Comment by kopijunkie** [comment]
We actually use Preact v8.5.2 in our project, but that might also be why we're not seeing this conversion.

**Comment by zpao** [comment]
Ah yea, that would do it. Preact doesn't do camelCase -> hyphenated. It looks like you may need to use `preact/compat`, based on https://preactjs.com/guide/v10/differences-to-react/#svg-inside-jsx

**Comment by kopijunkie** [comment]
Thanks for the advise. Will close this and look into that instead.
