### ISSUE TITLE
Feature request: Allow passing a React ref down to canvas element

### ISSUE THREAD

**Issue by tcchau** [zpao/qrcode.react#115]
It would be nice if the library could do this, so that we can avoid ```querySelector()``` and the like and use idiomatic React, i.e. ```useRef()```/```createRef()``` instead.

**Comment by RnzTejada** [comment]
Any suggestion?, i  have the same problem

**Comment by yaser-alazem** [comment]
You cannot use ref on the original QRCode component, as a work around it you can wrap the QRCode component with a div element and pass the rep into the div element like so:

```
              <div ref={qrCodeEl}>
                <QRCode
                  value='qr-value'
                  size={175}
                />
              </div>
```
and then you can get the QRCode canvas element like so:
`const canvas = qrCodeEl.current.children[0]`

**Comment by zpao** [comment]
It's possible to use a ref directly now with v4.
