### ISSUE TITLE
imageSettings props v0.9.3

### ISSUE THREAD

**Issue by milan-bc** [zpao/qrcode.react#119]
I tried to run v0.9.3 which is available on npm and also this one from github v0.9.2

`Warning: React does not recognize the `imageSettings` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `imagesettings` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

sample with error https://codesandbox.io/s/react-data-table-sandbox-forked-15fkg?file=/src/index.js 

looks like you pass it over as `restProps`, do you suggest to use v0.9.2? do you plan to fix this?

**Comment by zpao** [comment]
This was fixed in 1.0 - I'd recommend using that. I don't intend on releasing another 0.9.x (unless there's major demand). I'm going to close but I can reopen if need be

**Comment by milan-bc** [comment]
@zpao oh great, I notice on main github page there is listed last release as 0.9.2 on npm it's 0.9.3 but there is 1.0 cool, now it's clear will try that version :)

**Comment by zpao** [comment]
Ugh, GitHub stopped showing all tags as releases. I'll update that.

I published v1.0 to npm 10 months ago, so if it's not showing up there then they must be having some caching/consistency issues :(
