### ISSUE TITLE
Hardcoded width and height

### ISSUE THREAD

**Issue by jozan** [zpao/qrcode.react#12]
Is there a reason that width and height are "hardcoded" into style attribute? It's quite painful to try too get canvas responsive for different mobile screens. The only option is to use `!important` which is a bit hairy workaround.

```
canvas {
    height: auto !important;
    width: 100% !important;
    max-width: 300px;
 }
```

I get that rendering for retina (HiDPI) screens might be an issue to get a sharp image.

**Comment by kyle-rader** [comment]
@zpao 1. Thank you so much for building this.  This is exactly what I needed for a QR code based puzzle hunt game! 

@jozan You can dynamically change the size to anything you want using the `size` prop you pass to the component.  See this test component I built to play with the QR component.
```
import React from 'react';
import { Meteor } from 'meteor/meteor';
import QR from 'qrcode.react';

Game = React.createClass({

    getInitialState() {
        return {
            encode: 'Hello QR Codes!',
            size: 128
        };
    },

    handleEncodeChange(event) {
        this.setState({encode: event.target.value});
    },
    handleSizeChange(event) {
        this.setState(_.extend(this.state, {size: event.target.value}));
    },

    render() {
        return (
            <div className="custom-bg red-square">
                <br/>
                <div className="ui raised container segment transparent-bg">
                    <QR value={this.state.encode} size={parseInt(this.state.size)} />

                    <br/>
                    <div className="ui form">
                        <div className="fields">
                            <input type="text" defaultValue={this.state.encode} onChange={this.handleEncodeChange} />
                            <input type="text" defaultValue={this.state.size} onChange={this.handleSizeChange} />
                        </div>
                    </div>

                </div>
                
            </div>
        );
    }
});

```

**Comment by chidg** [comment]
Another hairy workaround, although one that doesn't involve CSS hacks. I made a  stateful responsive QRCode component by wrapping the QRCode.react component in a responsive div (a Bootstrap column), which I then wrapped with a Measure component from this library https://github.com/souporserious/react-measure. It worked well.

**Comment by Kiura** [comment]
Any updates on that? it could be useful if the component accepted string value for a size e.g. "30%", "300px" etc.

**Comment by zpao** [comment]
I added support for overriding style and adding a class name to make this work in v0.8. I opted not to make `size` take a percentage so that it was still easy to make `<canvas>` work and calculate the right sizing for pixel density, without having to measure the DOM or listen for resize events. If you want to support that you can using something like react-measure. Alternatively you can render to SVG now and get vectors for better handling in responsive layouts.

**Comment by beausmith** [comment]
Thanks for this great lib @zpao! 

I've found this issue when I was attempting to remove the hard-coded width and height attributes from the SVG output to have a responsive SVG. It's aways more ideal to not have to add more CSS to undo other styles.

I am aware that a class and/or styles can be added for responsive design. 

Un/fortunately, I'm using TypeScript and the definitions haven't been updated to allow additional props beyond the defaults: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/qrcode.react/index.d.ts

Thus… it sure would be great to have a `responsive` param to disable hard coded `width` and `height` attributes in the output…

```jsx
<QRCode responsive={true} value="foobar" />
```

Or — a breaking change, but simpler API — make the `size` param optional such that if not used, there are no `width` and `height` attributes on the output svg or canvas code.

My current solution with TypeScript is to use styled-components to create a wrapper `div` tag and use it to style the descendent `svg` element.

Posting here in the hopes it is helpful to others:

```jsx
import QRCodeReact from 'qrcode.react'
import React from 'react'
import styled from 'styled-components'

const ResponsiveSvgWrapper = styled.div`
  & > svg {
    display: block; /* svg is "inline" by default */
    height: auto; /* reset height */
    width: 100%; /* reset width */
  }
`

interface Props {
  value: string
}

const QRCode = ({ value }: Props) => (
  <ResponsiveSvgWrapper>
    <QRCodeReact renderAs="svg" value={value} />
  </ResponsiveSvgWrapper>
)

export default QRCode
```

**Comment by zpao** [comment]
@beausmith fair feedback. I don't think I'll add more props but what probably makes sense at some point is to stop supporting identical APIs for canvas and svg. It's convenient right now to be able to swap easily but they serve different purposes so probably not longer term.

**Comment by chnirt** [comment]
Thanks bro...save my life
