### ISSUE TITLE
white space around qrcode , i want to adjust the size of d

### ISSUE THREAD

**Issue by kooff88** [zpao/qrcode.react#121]
![image](https://user-images.githubusercontent.com/23475830/94359139-d5ceca80-00d7-11eb-8be0-2a07803c91ad.png)

the attribute  "includeMargin" is fixed now. 

Thank you!

**Comment by zpao** [comment]
QR Code spec actually has a fixed margin relative to the blocks. If you'd like to make it larger, you can add DOM nodes around and use CSS.
