### ISSUE TITLE
Round position pattern

### ISSUE THREAD

**Issue by sandbox4013** [zpao/qrcode.react#122]
How to change pattern for three position corners and use dots for data, instead of squares?
E.g.
![image](https://user-images.githubusercontent.com/49528851/94373364-b05cb380-010d-11eb-9f2b-238f8ff6e5ee.png)
Instead of:
![image](https://user-images.githubusercontent.com/49528851/94373273-0aa94480-010d-11eb-8d3e-71694f78443d.png)

**Comment by zpao** [comment]
It's not possible today. Going to use #124 as the canonical request.

**Comment by dev-alihaider** [comment]
Is it possible to achieve these in current package?
