### ISSUE TITLE
Document how to use image

### ISSUE THREAD

**Issue by poissoj** [zpao/qrcode.react#123]
I had to dig for the following information to understand why the QRCode I was generating was not working:

> There's an inherent risk to using an image in the QR Code. Specifically the risk is that it takes away too much of the actual scannable portion. By excavating (as seems to be the difference in your demos) you're actually taking away even more modules, not just the ones that are getting covered by the image. I don't have any protections in there to prevent embedding an image that covers up more than the error correction level can handle (the math got messy, transparent images change the math) so if you find yourself with a QR Code that doesn't scan, you need to correct that yourself. You have 2 options:
> 
> 1. Change the ratio of QR Code to image size. Make the image smaller or the QR Code bigger.
> 2. Increase the Error level (`level`), which will result in smaller modules with a better ability to handle covered areas.

_Originally posted by @zpao in https://github.com/zpao/qrcode.react/issues/100#issuecomment-582050218_

**Comment by poissoj** [comment]
This comment helped me figure out why my QRCode was invalid when I added an image inside.
I increased the error correction level, and it worked.
I think this deserves more visibility.

**Comment by LiamBorner** [comment]
Many, many thanks for pointing this out. Agreed, this detail should be added to the documentation somewhere

**Comment by zpao** [comment]
I added some docs for this. Hope they're better!
