### ISSUE TITLE
qr code scanning not working if we put icon or image at the center of qrcode

### ISSUE THREAD

**Issue by bipindubey-technoark** [zpao/qrcode.react#125]
```
<QRCode
                                    value={bookingResponse.qrCode}
                                    renderAs="svg"
                                    fgColor="#c92a23"
                                    // size="128"
                                    style={{
                                        display: 'block',
                                        height: 'auto',
                                        width: '100%',
                                    }}
                                    imageSettings={{
                                        src: '/images/PayMeIcon.png',
                                        height: '30',
                                      width: '30',
                                    }}
                                />
```

**Comment by zpao** [comment]
Copying my comment from #100:

> There's an inherent risk to using an image in the QR Code. Specifically the risk is that it takes away too much of the actual scannable portion. By excavating (as seems to be the difference in your demos) you're actually taking away even more modules, not just the ones that are getting covered by the image. I don't have any protections in there to prevent embedding an image that covers up more than the error correction level can handle (the math got messy, transparent images change the math) so if you find yourself with a QR Code that doesn't scan, you need to correct that yourself. You have 2 options:

> 1. Change the ratio of QR Code to image size. Make the image smaller or the QR Code bigger.
> 2. Increase the Error level (level), which will result in smaller modules with a better ability to handle covered areas.

I should add something to the readme to cover this but until then, hope this helps.
