### ISSUE TITLE
SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by kaiel2020** [zpao/qrcode.react#143]
I trying to download the QR code by click a button. And i get error:
`SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.`
This is my code for action click button download QR code.

```
const downloadQR = () => {
  const canvas = document.getElementById("123456");
  const pngUrl = canvas
    .toDataURL("image/png")
    .replace("image/png", "image/octet-stream");
  let downloadLink = document.createElement("a");
  downloadLink.href = pngUrl;
  downloadLink.download = "123456.png";
  document.body.appendChild(downloadLink);
  downloadLink.click();
  document.body.removeChild(downloadLink);
};
```
I found some solution is add `crossOrigin="anonymous"` to include image in QR code, refer [here](https://stackoverflow.com/questions/20424279/canvas-todataurl-securityerror).
Can u check it in your code from this [line](https://github.com/zpao/qrcode.react/blob/6aeb42abc26ffecc868b630b6ad8f507d2125813/src/index.js#L347)?

**Comment by kaiel2020** [comment]
@thaisuper

**Comment by flwzz** [comment]
the interface imageSettings can exntends  React.ImgHTMLAttributes, so we can provide other props to <img/> like  `crossOrigin='anonymous'`  to keep canvas not tainted.

**Comment by javaxiu** [comment]
> the interface imageSettings can exntends React.ImgHTMLAttributes, so we can provide other props to `````img`` like `crossOrigin='anonymous'` to keep canvas not tainted.

so is this feature available now ?
