### ISSUE TITLE
how to control margin size

### ISSUE THREAD

**Issue by ixqbar** [zpao/qrcode.react#147]
how to control margin size

**Comment by listao** [comment]
I have this same question as well. It seems like it's a fixed value at the moment. If we could have a prop to control this margin size, I think that'd be great.

**Comment by Aumeeb** [comment]
Directly set the border : 6px solid #fff on that Component without need property includeMargin
![image](https://user-images.githubusercontent.com/26300918/174009245-d4f47a1c-04c4-4b33-9d31-e8b4a6202259.png)

**Comment by zpao** [comment]
`marginSize` was added in #281 and will be available in v4.x
