### ISSUE TITLE
Prints very bad (on paper)

### ISSUE THREAD

**Issue by nikbelikov** [zpao/qrcode.react#15]

**Comment by dcousens** [comment]
I don't think that is related to this library.

**Comment by zpao** [comment]
Agreed, going to close out. You probably just want to draw it bigger.

Alternatively, we could potentially render svg instead of canvas - would probably print better but have other tradeoffs.

**Comment by geoalexidis** [comment]
FYI:

I had this same issue bu was abtle to swtich to svg for the print and remain canvas for the browser.

Thanks @zpao for providing us with this option!
