### ISSUE TITLE
Multiple images to be added in QRCode

### ISSUE THREAD

**Issue by kirtishjain9** [zpao/qrcode.react#153]
Can we add more than one image in the generated qr code? if Yes, then how that would be possible and if No then can this feature be added in near future?

I've added one image at centre of qr code generated but need one more image to be added at top middle of the QRcode?

Please let me know your answer and feedback on this.

Thanks & Regards
KJ

**Comment by zpao** [comment]
I appreciate the feature request but I'm not going to add that.

**Comment by Alex-Anev** [comment]
> Can we add more than one image in the generated qr code? if Yes, then how that would be possible and if No then can this feature be added in near future?
> 
> I've added one image at centre of qr code generated but need one more image to be added at top middle of the QRcode?
> 
> Please let me know your answer and feedback on this.
> 
> Thanks & Regards
> KJ

Try concatenating all the images together and put them in the QR code as one image
