### ISSUE TITLE
Error: 'default' is not exported by node_modules/qrcode.react/lib/index.js

### ISSUE THREAD

**Issue by sibelius** [zpao/qrcode.react#155]
I'm getting the following error when trying to build this package using rollup

```jsx
Error: 'default' is not exported by node_modules/qrcode.react/lib/index.js
```

https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module

does it make sense to upgrade this package to be built using rollup, so we have commonjs and esm entrypoints?

**Comment by zpao** [comment]
I'm not opposed. I know @realityking was interested in ESM as well in #56.

**Comment by realityking** [comment]
@zpao If you’re up for merging #56 I’d be happy to clean that up & create the plumbing for ESM support. What do you think?

**Comment by meabed** [comment]
@realityking I have migrated and bundled the library with esm support here 
- https://unpkg.com/browse/@devmehq/react-qr-code@1.0.2/
- https://github.com/devmehq/react-qr-code
