### ISSUE TITLE
Unable to pass parameter

### ISSUE THREAD

**Issue by OrganicOat** [zpao/qrcode.react#156]
The QRCode is look like unable to pass it value to function, do youguys has any Idea about this?

**Comment by zpao** [comment]
Do you have an example?

**Comment by OrganicOat** [comment]
The (e) is undefined when try to pass it into my function, that value work only when scan.

<QRCode size={113} value="hihi" onClick={(value, e) => ZoomInQRCode(e)}  />

function ZoomInQRCode(e) {
     console.log(e)
}

**Comment by zpao** [comment]
`e` is going to be undefined. We don't expose an `onClick` so you're just getting the raw `onClick` from the DOM, and the first argument is the event.
