### ISSUE TITLE
qr.js has been hijacked 

### ISSUE THREAD

**Issue by tiero** [zpao/qrcode.react#168]
History disappeared and force pushed https://github.com/shtylman/qr.js

Can you vendor the old codebase and do not depend on NPM updates please?

**Comment by tiero** [comment]
That's very important @zpao, hundreds of crypto project using this library are potentially at risk to be hacked next time you pull/bump dependency. I sugget you to publish and vendor the code your current npm package is including from qr.js

**Comment by Sloaix** [comment]
I think just NPM account was attacked, the original repo should be https://github.com/defunctzombie/qr.js

**Comment by meabed** [comment]
I use the library and it seems unmaintained.
if any interested, I have updated the library and migrate it to typescript https://github.com/devmehq/react-qr-code

**Comment by mifi** [comment]
an alternative to qr.js could be https://github.com/soldair/node-qrcode
