### ISSUE TITLE
Warning on Browser Console each time I used the tool.

### ISSUE THREAD

**Issue by Felistus** [zpao/qrcode.react#170]
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://reactjs.org/link/unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://reactjs.org/link/derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 18.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: QRCodeCanvas

**Comment by zuhijan** [comment]
same problem

**Comment by feaswcy** [comment]
+1

**Comment by D1no** [comment]
Just use this: https://github.com/Bunlong/next-qrcode
