### ISSUE TITLE
i updated react-dom ^17.0.2 ,get error

### ISSUE THREAD

**Issue by ChenYCL** [zpao/qrcode.react#171]
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/25706676/155075363-24a9bff4-95db-4f13-99bd-a720f9bd64d3.png">

**Comment by zpao** [comment]
Upgrading React shouldn't have had any impact here - this isn't related to ReactDOM. The only way this happens is if you pass `null` to the `value` prop, which is explicitly an error and has been in this library for a long time. Even if we add explicit handling of that, I would throw an error.

Please check the values you're passing in. If those are not `null` and you're seeing this error, then please provide a test case I can reproduce with.

**Comment by ChenYCL** [comment]
sorry,when i remove node_module directory and reinstall ,no problem!
