### ISSUE TITLE
UNSAFE_componentWillReceiveProps Warning

### ISSUE THREAD

**Issue by rafaelcsva** [zpao/qrcode.react#175]
Hi. 
I'm facing this warning when i use this component:
![warning](https://user-images.githubusercontent.com/24235497/158653583-98b9e4d9-5696-4e70-bde4-1f3f80e4b06c.png)

I'm think it have to do with line 248, maybe changing it to:
```
useEffect(() => {
    // Always update the canvas. It's cheap enough and we want to be correct
    // with the current state.
    update();
 }, [...availableProps]);
```
could solve it, seens it just works as expected because it will update the component whenever an external prop in changed, not sure..

React Version: 17.0.2

**Comment by zpao** [comment]
V3 will come out soon (it's what you see in main right now) and will no longer be using the unsafe lifyscyle methods. Will leave this open until that's shipped.

**Comment by zpao** [comment]
Ok, v3 is out. Give it a whirl
