### ISSUE TITLE
Using QRCodeSVG I get: Element type is invalid: expected a string (for built-in components) 

### ISSUE THREAD

**Issue by notjulian** [zpao/qrcode.react#176]
Hello @zpao,
first of all thanks for this lib

using QRCodeSVG and QRCodeCanvas I'm getting this error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

what I'm doing wrong?
[example](https://codesandbox.io/s/silly-swartz-ncfhsc?file=/src/App.js)

QRCode component is working fine ...

thanks

**Comment by notjulian** [comment]
just a problem in the import
`import QRCodeSVG from "qrcode.react"`

[*](https://codesandbox.io/s/floral-rgb-hgizgk?file=/src/App.js)

**Comment by zpao** [comment]
Sorry for the confusion! The readme on the repo page is for the in-progress v3. For the latest release (v2.0.0) you can view the readme at https://github.com/zpao/qrcode.react/tree/v2.0.0.

The named exports is a new feature which will be available in v3.
