### ISSUE TITLE
Additional props to QR code components not supported in Typescript types

### ISSUE THREAD

**Issue by brookback** [zpao/qrcode.react#186]
The docs says:

> qrcode.react will pass through any additional props to the underlying DOM node (<svg> or <canvas>).

But this is not supported in the props type for the canvas and SVG components:

https://github.com/zpao/qrcode.react/blob/main/src/index.tsx#L21-L38

This causes any additional props passed to be an error when running `tsc`.

A solution could probably be:

```tsx
function QRCodeCanvas(props: QRProps & React.CanvasHTMLAttributes<HTMLCanvasElement>) {
// pick all QRProps to be used, and spread the rest
```

**Comment by zpao** [comment]
Hmm, good catch. I wonder if I can use `interface` instead of `type` here: https://github.com/zpao/qrcode.react/blob/main/src/index.tsx#L21-L38

**Comment by Janaka-Steph** [comment]
> Hmm, good catch. I wonder if I can use `interface` instead of `type` here: https://github.com/zpao/qrcode.react/blob/main/src/index.tsx#L21-L38

I don't see why you could not use Interface

**Comment by brookback** [comment]
@zpao The `type` vs `interface` thing isn't relevant here, I think. It's just a matter of taste. You need to allow the HTML attributes for the components you export though, like in my original comment:

```ts
const Component = (props: YourProps & React.CanvasHTMLAttributes<HTMLCanvasElement>) => {
  const { your, props, here, ...canvasProps } = props;

  return <canvas {...canvasProps}></canvas>;
}
```

**Comment by zpao** [comment]
Gotcha. I haven't spent much time with Typescript, but Flow had explicit support for inexact object types. This allowed the specified props be typechecked while letting anything else through, which I took advantage of. I was hoping TS had that as well (and for some reason thought that was what `interface` did).

But it looks like the old TS types somebody had written does what you're saying too (https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3ba3c3f2ff22310a22a4874b6f76826d3fbc5e5b/types/qrcode.react/index.d.ts#L31-L37), so I guess that's what we'll do.
