### ISSUE TITLE
Uncaught DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by Lukashev** [zpao/qrcode.react#198]
Hello, i try to export canvas to png with embedded image from S3 bucket. I use **file-saver** library for downloading images.
I also tried separately getting resource with crossOrigin="anonymous" setup, not working, then I tried on svg instead canvas, but again, i got png without embedded image. Maybe someone has workaround and can provide possible solution. Thanks in advance.

**Comment by zpao** [comment]
Duplicate of #143
