### ISSUE TITLE
3.0.2 not support IE browser

### ISSUE THREAD

**Issue by gdccwxx** [zpao/qrcode.react#201]
When I upgrade package 1.0.1 -> 3.0.2. I found it can't support IE browser.

because ES5 files contains arrow function.
<img width="2345" alt="image" src="https://user-images.githubusercontent.com/28426137/173272192-d78df314-0c7f-432c-8eca-35675c7e3ae2.png">

**Comment by zpao** [comment]
IE11 reaches end of life this week. I'm not going to support it. I'm sorry if you need to support IE11 beyond now.

FWIW, there's little functionally different between these versions. Mostly it's internal/dependency changes - check the changelog for the details. As long as you don't need the support for newer versions of React, then you're probably safe to stay on the old version.

You're welcome to fork as needed. I use tsup for generating the build files - you may have some luck looking at its ES5 support: https://tsup.egoist.sh/#es5-support
