### ISSUE TITLE
Data too long

### ISSUE THREAD

**Issue by genesisemmloh** [zpao/qrcode.react#225]
i wanted to pass a VCard with an image64 based 
its not possible with this library?
 example 👍 

BEGIN:VCARD
VERSION:3.0
FN;CHARSET=UTF-8:Emmanuel Lohora
N;CHARSET=UTF-8:Lohora;Emmanuel;;;
EMAIL;CHARSET=UTF-8;type=WORK,INTERNET:Emmanuel.Lohora@loacker.cc
PHOTO;ENCODING=b;TYPE=image/jpg:/9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDtv7M00RSBb1ScHgH2rwJJpU8bJG1zMYBdgEbzjGa+i5rALotw4t402uckDmvm2/SVfFkiwKxnM2Iwo/iJwP1pIwg3LpY9r1288P2tgVmvljlypCs2COetQaLLpM9zObbVEniMx+ZWB649K4PUPh3qryLNc6zHPMw3SkqSc/1rj9l94Q8QJMGbdFJndyFlUHkH1BFZqSbsmdEqE4xu0e/alBpsIEi3e35sEioEi0yW7tiLoklRnFU9RkiSKGaOPfG4Vtp962PEFta2upab9nVNskAOB9atJ2vc4vaPsdlq1pINHv3EnBJYLjivmGz3N8Q7cCRVkN2QpYZAPOP1xXtb+MdSutcTQpY0+z3EHmtJ3Ge1eE3Rks/iGhXlkvgR/wB9VbW5rSmnJM9MvzqzWq2895F9oldgJUGMgdM4HH4VzOu6MupTabp9xIxPmkM69fungfUgc1Vu5LP+0pXn1G7hvI9zu7vjYQcbNuevAHv1qWXxFFFqul6rLE4s4LhHwThpjkZx/sgcn1riUJKaR7E5w9m3ueo6nok+63tLeIyP5S4RBk8cf0rQ8TWC2+rWDy4RmgCge4p+m669rdPMsay7ujE9QRkY9q57U9buNa1y1e4+URybVXsBXelofPJprzO5/wCEMj+1Rz/asOqgAhBmvmvXrd4fiJexEB3t7tiW9QpzX0AddnZHPnP8vTmvB7iKaTxHql48TnMhwSDzk849adNOUrM6PdS91GvZzWOpXOq65rgtVRJUih3xjcWAPyqD7Y5NcZrGoTa5qDzFAkSHZEoHCL6e578VY/sqZ5nnliLBn3Kg3bVz/kZp81rLFkfZ5GVZBny84P0/xp+xjzObN1UfIoLYv+G/FWo+H3SPJubMHBtWJyB6qf4ePw9q9w0XQtE8T2FjrWm6g7QsdxBwGRx1Vh2Ir54ls7mT5Es5hJI2UY5GF54Pb8a6j4eahfafrX2LbcxWt1gkEHAkUdfxGR+VKfZGbpxfvNH/2Q==
TEL;TYPE=CELL:+43 6648321470
TEL;TYPE=WORK,VOICE:+4355235021164
TITLE;CHARSET=UTF-8:Software Engineer
ROLE;CHARSET=UTF-8:Digitalisation & Innovation
ORG;CHARSET=UTF-8:Loacker Recycling GmbH
URL;type=WORK;CHARSET=UTF-8:https://www.loacker.cc/
REV:2022-06-29T15:22:19.478Z
END:VCARD

**Comment by zpao** [comment]
Are you running into a specific issue? In a quick test it seems like all of the data is getting encoded into the QR Code fine.

**Comment by GaroGabriel** [comment]
![Screenshot 2022-12-02 135223](https://user-images.githubusercontent.com/66430651/205265663-e36bd66a-9a11-412f-ad07-c43e24a82903.png)

**Comment by zpao** [comment]
As noted, capacity of QR Codes is limited. See also my comment in https://github.com/zpao/qrcode.react/issues/302#issuecomment-1684382813 which has some more detail.
