### ISSUE TITLE
How to add some text in qr code

### ISSUE THREAD

**Issue by abuzarshakir** [zpao/qrcode.react#233]
I'm using qrcode.react for my project. I want to download qr code in png file with some text in qr image. Please guide me how can I achieve this. I want  qr code to look like this after downloading.

![picture](https://user-images.githubusercontent.com/109339303/179179591-1dcfac0d-3032-4fbe-9341-f21f7d854b64.png)
This is the function to download qr code.

`  const downloadQRCode = () => {

        const qrCodeURL = document.getElementById('qrCodeEl')
          .toDataURL("image/png")
           .replace("image/png", "image/octet-stream");

        let aEl = document.createElement("a");

        aEl.href = qrCodeURL;
        aEl.innerText = props.qrName;
        aEl.title = props.qrName;
        aEl.download = `${props.qrName}.png`;
        document.body.appendChild(aEl);
        aEl.click();
        document.body.removeChild(aEl);

    } `
    This is QRCode component.
    
    ` <QRCode
          id="qrCodeEl"
           size={150}
           value={qrCodeText}
        />`

**Comment by abuzarshakir** [comment]
Still, waiting for the solution.

**Comment by stelli98** [comment]
Hi i got this issue too. 
I found another alternative solution from [this stackoverflow comment](https://stackoverflow.com/questions/3318565/any-way-to-clone-html5-canvas-element-with-its-content), that is to create new canvas, and copy the canvas that is generated from qrcode.react to the new canvas. Here is my example : 

 ```
const onDownload = () => {
    const oldCanvas = qrRef.current.querySelector('canvas');

    const newCanvas = document.createElement('canvas');
    const context = newCanvas.getContext('2d');

    newCanvas.width = 320;
    newCanvas.height = 320;

    // create white background and center the text
    context.font = '14px Roboto';
    context.fillStyle = 'white';
    context.textBaseline = 'middle';
    context.textAlign = 'center';
    context.fillRect(0, 0, 320, 320);

    // create style for text inside canvas
    context.fillStyle = '#4A4A4A';
    context.fillText('Scan Here to Order', newCanvas.width / 2, 20);
   // copy oldCanvas to newCanvas
    context.drawImage(oldCanvas, 35, 35, 250, 250);
    context.fillText('Thank You, Have a nice day ', newCanvas.width / 2, 305);

    const image = newCanvas.toDataURL('image/png');
    const anchor = document.createElement('a');
    anchor.href = image;
    anchor.download = `qr-code.png`;
    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);
  };
```

I hope it can solve your case @abuzarshakir

**Comment by abuzarshakir** [comment]
> Hi i got this issue too. I found another alternative solution from [this stackoverflow comment](https://stackoverflow.com/questions/3318565/any-way-to-clone-html5-canvas-element-with-its-content), that is to create new canvas, and copy the canvas that is generated from qrcode.react to the new canvas. Here is my example :
> 
> ```
> const onDownload = () => {
>    const oldCanvas = qrRef.current.querySelector('canvas');
> 
>    const newCanvas = document.createElement('canvas');
>    const context = newCanvas.getContext('2d');
> 
>    newCanvas.width = 320;
>    newCanvas.height = 320;
> 
>    // create white background and center the text
>    context.font = '14px Roboto';
>    context.fillStyle = 'white';
>    context.textBaseline = 'middle';
>    context.textAlign = 'center';
>    context.fillRect(0, 0, 320, 320);
> 
>    // create style for text inside canvas
>    context.fillStyle = '#4A4A4A';
>    context.fillText('Scan Here to Order', newCanvas.width / 2, 20);
>   // copy oldCanvas to newCanvas
>    context.drawImage(oldCanvas, 35, 35, 250, 250);
>    context.fillText('Thank You, Have a nice day ', newCanvas.width / 2, 305);
> 
>    const image = newCanvas.toDataURL('image/png');
>    const anchor = document.createElement('a');
>    anchor.href = image;
>    anchor.download = `qr-code.png`;
>    document.body.appendChild(anchor);
>    anchor.click();
>    document.body.removeChild(anchor);
>  };
> ```
> 
> I hope it can solve your case @abuzarshakir

**Comment by abuzarshakir** [comment]
Solved my problem. Thank you so much @stelli98
