### ISSUE TITLE
React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

### ISSUE THREAD

**Issue by 1003865572** [zpao/qrcode.react#25]
warning.js:36Warning: QRCode: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.

**Comment by BrockWills** [comment]
Looking at commit history, this appears to have been fixed on master, but a new npm release would be good

**Comment by dcousens** [comment]
This has been fixed and released in 0.7.0.   Good to close.

**Comment by zpao** [comment]
Indeed, thanks for the followup.
