### ISSUE TITLE
NVDA screen reader does not detect QR code SVG

### ISSUE THREAD

**Issue by ultrapabs** [zpao/qrcode.react#283]
The [NVDA screen reader](https://www.nvaccess.org/download/) for Windows does not detect the QR code SVG when moving through objects on the screen. When moving across elements it, NVDA skips the SVG entirely. See attached video for example (QR code in example is expired one time link).

https://user-images.githubusercontent.com/10451187/206581398-0944995f-cd11-4ae7-9faf-ef4bb6e01a1d.mov

**Comment by ultrapabs** [comment]
Forgot to add - putting a `<title>` within the `svg` resolves the issue and allows NVDA to detect the element. Working on a fix.

**Comment by ultrapabs** [comment]
[PR added](https://github.com/zpao/qrcode.react/pull/284) - other possible solution could be to add a new attribute such as `accessibleName` that converts to a `<title>` for `svg` and `aria-label` for `canvas`, but the `canvas` case is already handled by `otherProps` forwarding `aria-label`.

**Comment by zpao** [comment]
#284 fixed this. Will ship in v4.0.0 (unless I end up shipping a 3.2 at some point)
