### ISSUE TITLE
QRCodeSVG imageSettings.src cannot load local image

### ISSUE THREAD

**Issue by nehssss** [zpao/qrcode.react#290]
<img width="797" alt="image" src="https://user-images.githubusercontent.com/52525885/234747500-d2571f64-47cb-43fa-b164-33aab7eefe65.png">
When I try to import the local image to QRCodeSVG, it cannot load the image
<img width="257" alt="image" src="https://user-images.githubusercontent.com/52525885/234747612-84286add-7295-4f47-8038-4758cdd41455.png">
Here is my dependencies
<img width="330" alt="image" src="https://user-images.githubusercontent.com/52525885/234747691-d0de6547-28a2-4e8c-97ac-918826f92b10.png">

**Comment by yao-tx** [comment]
@nehssss 

I'm using Next.js here but hopefully this will help you with using local images in your QR logo.

Simply store your image in the public folder, and just set the src to "team_logo.png", no need for specifying the directory.

Alternatively, what you can do is import the image first such as:

`import TeamLogo from "./team_logo.png";`

and then in the "src" property, set it to TeamLogo.src, like the following:

```
...
imageSettings={{
  src: TeamLogo.src,
  ...
}}
...
```

All these work for me in Next.js 13.
