### ISSUE TITLE
3.1.0 has no `marginSize` prop in `QRProps`

### ISSUE THREAD

**Issue by na2na-p** [zpao/qrcode.react#293]
Thanks for a great and cool product!
I found something that could be improved here that might make it better.

# AsIs

Release 3.1.0 has no `marginSize` prop in `QRProps`.
(Image from `node_modules/qrcode.react/lib/index.d.ts`)
![image](https://github.com/zpao/qrcode.react/assets/49822810/cdab2073-c2dd-4f66-87e9-85041ee43679)

## How to reproduce

1. `npm install qrcode.react`
2. Check `node_modules/qrcode.react/lib/index.d.ts`

# ToBe

Even if introduced as an npm package, `marginSize` prop is available as `QRProps` as well as the `trunk` Branch.
(Image from `src/index.tsx`)
![image](https://github.com/zpao/qrcode.react/assets/49822810/fdf53fde-9581-49da-96fb-15fb960e8b12)

Could you also update the registration on npmjs.com?
https://www.npmjs.com/package/qrcode.react

Thank you!

**Comment by OriginRing** [comment]
Guess it should be supported in version 3.2.0, when will the new version be released? @zpao

**Comment by zpao** [comment]
Ah yea, sorry this wasn't shipped in 3.x! I'll get 4.0 out with this (but probably won't bother with 3.x)
