### ISSUE TITLE
Named export 'QRCodeSVG' not found.

### ISSUE THREAD

**Issue by jaythakur345** [zpao/qrcode.react#299]
Hello @zpao,
first of all thanks for this lib

using **QRCodeSVG** I'm getting this error:

    import { QRCodeSVG } from "qrcode.react";
         ^^^^^^^^^
    SyntaxError: Named export 'QRCodeSVG' not found. The requested module 'qrcode.react' is a CommonJS module, which may not 
    support all module.exports as named exports.
    CommonJS modules can always be imported via the default export, for example using:

    import pkg from 'qrcode.react';
    const { QRCodeSVG } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

```
dependencies:{
         "@types/node": "^18.11.9",
         "@types/react": "^18.0.8",
         "@types/react-dom": "^18.0.3",
         "react": "^18.2.0",
         "react-dom": "^18.2.0",
         "ts-node": "^10.9.1",
         "qrcode.react": "^3.1.0",
}
```

thanks

**Comment by zpao** [comment]
It looks like Node isn't detecting the `main` & `module` fields correctly there. Actually, I'm not sure if Node ever supported `module`. There generally isn't a great reason to use this directly in Node AFAIK but doesn't hurt to support it. I just put up #301 which should do the trick.
