### ISSUE TITLE
QR Code Unscannable When Length Exceeds Certain Characters

### ISSUE THREAD

**Issue by Basavarajrp** [zpao/qrcode.react#302]
**Issue Description:**
I'm encountering an issue with the QR code generation library in React. When passing text to the QR code that exceeds a certain character length, the generated QR code becomes unscannable. However, if I limit the character length to a smaller value, the QR code works correctly and can be scanned without any issues. Here's a detailed description along with a minimal code example to reproduce the issue.

**Steps to Reproduce:**

The child Component with the qr code is unscannable.

```
import QRCode from 'qrcode.react';

type qrPropsType = {
  height?: number;
  width?: number;
  qrvalue: string;
  size?: number;
};

export default function QRComponent(qrProps: qrPropsType) {
  const memberID = qrProps.qrvalue;
  const imageSetting = {
    src: 'image_link',
    excavate: true,
    height: qrProps.height,
    width: qrProps.width,
  };
  return <QRCode value={memberID} size={qrProps.size} renderAs="canvas" imageSettings={imageSetting} />;
}
```

This Works:
```
import QRCode from 'qrcode.react';

type qrPropsType = {
  height?: number;
  width?: number;
  qrvalue: string;
  size?: number;
};

export default function QRComponent(qrProps: qrPropsType) {
  const memberID = qrProps.qrvalue;
  // const memberID = '12345';
  const imageSetting = {
    src: ''image_link",
    excavate: true,
    height: qrProps.height,
    width: qrProps.width,
  };
  return <QRCode value={memberID.slice(0, 4)} size={qrProps.size} renderAs="svg" imageSettings={imageSetting} />;
}

```

**Comment by zpao** [comment]
This is a limitation of QR Codes generally. [See the Information Capacity section of the Wikipedia article](https://en.wikipedia.org/wiki/QR_code#Information_capacity) as well as the note from our Readme:

> `qrcode.react` supports encoding text only, in a single segment. The encoding library being used does minimal detection to determine if the text being encoded can follow an optimized path for Numeric or Alphanumeric modes, allowing for more data to be encoded. Otherwise, it will encode following Byte mode.

Note that if you're encoding a lot of unicode, that is likely using 2 bytes per character so you have less capacity than you may think.
