### ISSUE TITLE
Making the qrcode size percentage based

### ISSUE THREAD

**Issue by ifenega** [zpao/qrcode.react#309]
the type declaration for the size for prop size is currently number and so i cant pass percentage as string. is there any way around this

**Comment by zpao** [comment]
I'm not particularly keen on supporting that and doing more parsing & math but I'm open to hearing more. Can you explain why you need this in more detail? You can do the math yourself today to achieve the same effect, which I do recognize isn't the most ergonomic.

**Comment by zpao** [comment]
Based on working through the linked PR, I'm just going to go ahead and close this out. I'm not going to do this. Use `style` or `className` to override the pixel based styles. It works nicely for SVG.
