### ISSUE TITLE
No option to provide version

### ISSUE THREAD

**Issue by jashwant** [zpao/qrcode.react#311]
If the data has smaller length, it defaults to QR code version 1.

But we need QR code on curved/cylindrical surface and we would like to have alignment pattern in Qrcode for better scanning. Alignment pattern only started since version 2. So, we would like to have an option to pass version instead of auto selecting the version.

[node-qrcode](https://github.com/soldair/node-qrcode#mixed-modes) has the option to pass qversion.

**Comment by zpao** [comment]
I'm game. It would require just a little bit of work.

We currently call this:
https://github.com/zpao/qrcode.react/blob/2e1f5a5ecc11378d48f14b548c0a28d0474f97fe/src/third-party/qrcodegen/index.ts#L44-L47

We'd need to do that manually and call `encodeSegments` with the `minVersion` arg set:
https://github.com/zpao/qrcode.react/blob/2e1f5a5ecc11378d48f14b548c0a28d0474f97fe/src/third-party/qrcodegen/index.ts#L71-L73

**Comment by zpao** [comment]
Do you want to provide a precise version or would you be ok specifying a minimum version but allowing a higher one if needed? It sounds like the latter from what you wrote.

**Comment by jashwant** [comment]
@zpao , Yes a minimum version. Thanks for the quick work around it.
