### ISSUE TITLE
TS: `QRCodeCanvas` and `QRCodeSVG` are not typed as React components

### ISSUE THREAD

**Issue by ipanasenko** [zpao/qrcode.react#312]
Generated types for `QRCodeCanvas` and `QRCodeSVG` are just functions.
![image](https://github.com/zpao/qrcode.react/assets/576152/905fbcab-6809-49c8-9b48-3a8b8818a57d)

While it works as expected in most cases, it's not possible to pass implicit React props, e.g. `ref`:
![image](https://github.com/zpao/qrcode.react/assets/576152/f352dfc8-d771-4240-8643-197b95ada7df)

They should have proper `React.FunctionComponent` type to allow this

**Comment by zpao** [comment]
These are currently typed fine - `ref` was not supported. #202 added proper support for refs and will ship in the next major version.
