### ISSUE TITLE
`level` prop type is string

### ISSUE THREAD

**Issue by minsoo-web** [zpao/qrcode.react#341]
I was using version 3.1.0 and noticed that the prop named `level` has a type of `string`.

![image](https://github.com/zpao/qrcode.react/assets/57122180/ebe0a5aa-39b7-4bce-9ae9-6eba25700182)

I thought it would be nice to contribute, so I checked the source code (trunk branch) and found that the version is the same, 3.1.0, but the type is enhanced with `ErrorCorrectionLevel`.

I wonder if it hasn't been redistributed yet or if it's planned.

**Comment by zpao** [comment]
I appreciate the attempt to contribute! The types are updated in `trunk` but haven't been shipped. They'll go out in v4, hopefully within a few weeks.

**Comment by minsoo-web** [comment]
Thanks for the reply, I'm really looking forward to v4!!! Thanks for making such a great library.
