### ISSUE TITLE
Please add support for PNG

### ISSUE THREAD

**Issue by johann1301s** [zpao/qrcode.react#342]
Please add support for PNG format.

I rarely prefer PNG over SVG, but I have discovered that many phones now support "tap-and-hold" over a QR code if it is a PNG.

This is especially useful when the value passed to the QR code is not a valid url, like in the case of eSIM.

eSIM does not use the http protocol, but an activationCode that is not possible to navigate to using html links.

When you "tap-and-hold" on an eSIM QR code that is PNG, it gives you an option to start the eSIM setup. See picture below.

This does not work with SVG.

![IMG_0555](https://github.com/zpao/qrcode.react/assets/25029220/3e1e24ee-2c98-4c7a-a529-78c7ed1dcfd1)

**Comment by zpao** [comment]
Have you tried using the canvas component? Canvases are typically treated much more like native images and can be saved directly as PNGs in most browsers at least on desktop. It's also possible to do that extraction via code. v4 needs to ship with proper ref support (soon) but with that you can do something like https://github.com/zpao/qrcode.react/blob/0f6c240e4943e54461c8ada8eb184f739c4eed58/examples/download.tsx#L15-L21.

That's pretty much exactly what I would do if I were to add generic png/jpg/etc support. I'm not going to bloat this library with client-side image encoding libraries and I don't know that I want to maintain the wrapper component myself. I'll leave this open and may even write an example that shows doing this with v4 when it ships. It's possible (however unlikely) that I decide it's simple enough to ship in the library itself.

But really, if what you want is a PNG, then doing this client-side is probably not the best way to do it. I would probably recommend do it server-side in a lambda or some other stateless endpoint (eg Vercel/Netlify endpoint).

**Comment by zpao** [comment]
Put up a PR with an example (requires trunk, or v4 soon). I tested it on iOS with a value that matches the format for eSIM and it did bring up the expected UI you showed. But through this, I decided I won't add it to the core but leave it for user space since it's a far less common need and may have issues to work out / support that I don't want to do. Hope that helps!
