### ISSUE TITLE
Is there a planned release date for the next version?

### ISSUE THREAD

**Issue by yoyo837** [zpao/qrcode.react#344]
Nearly two years have passed since the last version was released. During this time, many PRs have been merged, but there seems to be no intention of releasing them.

**Comment by kiner-tang** [comment]
+1

**Comment by li-jia-nan** [comment]
+1

**Comment by zpao** [comment]
soon!

**Comment by kiner-tang** [comment]
> soon!

@zpao Is there a clear timetable for the release

**Comment by zpao** [comment]
No. I wanted to get a couple other documentation/website changes in but haven't had a chunk of time to do that. I'm trying to make that time this week though, so let's see!

**Comment by josephnle** [comment]
@zpao Is there anything we can help with? There are a handful of features/fixes I'd like to use. Would it be possible to at least release a minor version?

**Comment by dmausttruefit** [comment]
Also interested as I'd like to improve SVG accessibility with the `title` prop

**Comment by idaninho** [comment]
i would like to know about it too! need the qr code with cross origin option :)

**Comment by raghavsethi** [comment]
@zpao thanks so much for your work on this, but also needed some features merged recently and wanted some rough estimate of when you could do a new (even minor) release!

**Comment by zpao** [comment]
v4.0.0 has been published. Enjoy!

**Comment by raghavsethi** [comment]
Thank you! <3
