### ISSUE TITLE
Support for server components

### ISSUE THREAD

**Issue by kachkaev** [zpao/qrcode.react#347]
👋 @zpao! Just curious if you have any plans to support server components. I am experimenting with [og images in Next.js](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/opengraph-image) ([`vercel/satori`](https://github.com/vercel/satori)), writing something like this:

```tsx
import { ImageResponse } from "next/og";
import { QRCodeSVG } from "qrcode.react";

export function GET(): Response {
  return new ImageResponse(
    (
      <div tw="flex w-full h-full items-center justify-center bg-[#cfc]">
        <QRCodeSVG
          value="https://example.com"
          width={100}
          height={100}
          includeMargin={true}
        />
      </div>
    ),
    {
      width: 200,
      height: 200,
    },
  );
}
```

This code works! – **UPD: not quite, see https://github.com/zpao/qrcode.react/issues/347#issuecomment-2611289318**

![image](https://github.com/zpao/qrcode.react/assets/608862/b49cf84f-230d-4d12-83c6-75a23f5a5c33)

However, there are warnings during `next dev`, `next build` and `next start` If I add `export const runtime = "edge";` to the file:

```trace
 ⚠ ./node_modules/.pnpm/qrcode.react@3.1.0_react@18.3.1/node_modules/qrcode.react/lib/esm/index.js
Attempted import error: 'useRef' is not exported from 'react' (imported as 'useRef').

Import trace for requested module:
./node_modules/.pnpm/qrcode.react@3.1.0_react@18.3.1/node_modules/qrcode.react/lib/esm/index.js
./app/test/route.tsx

./node_modules/.pnpm/qrcode.react@3.1.0_react@18.3.1/node_modules/qrcode.react/lib/esm/index.js
Attempted import error: 'useEffect' is not exported from 'react' (imported as 'useEffect').

...
```

Regardless of Next.js intricacies, it seems that `qrcode.react` lacks React server component support. This line imports hooks that are [not available](https://react.dev/reference/rsc/server-components#adding-interactivity-to-server-components) on the server:
https://github.com/zpao/qrcode.react/blob/df6d610447135ec197b33c4ee01f2c43efa06278/src/index.tsx#L7

What do you think about splitting canvas and svg implementations into two files? If we import an SVG, it can be server-rendered. If it’s a canvas, there is `"use client"` on top. I reckon that both `QRCodeCanvas` and `QRCodeSVG` can be still re-exported from `src/index.tsx`, so the change is non-breaking.

**Comment by zpao** [comment]
Nothing against it at all. IIRC the issue with splitting is that it requires restructuring the actual encoder to work with our current toolchain.

> This line imports hooks that are [not available](https://react.dev/reference/rsc/server-components#adding-interactivity-to-server-components) on the server

I don't see any actual documentation on what can or cannot be imported in server components. I can start a next project and go through trial and error, but that's not ideal.

**Comment by kachkaev** [comment]
Cool! 

> I don't see any actual documentation on what can or cannot be imported in server components.

I believe that it applies to anything that’s stateful. E.g. `useEffect`, `useState`, `useCallback`, etc.

https://github.com/zpao/qrcode.react/pull/188 is a step in the right direction, it’s just missing `"use client"` in `canvas.tsx`. We can push the suggestion to @caub’s PR or I can create a new PR from scratch if that’s easier. What would you prefer?

**Comment by kachkaev** [comment]
Ping @zpao 👋 
Happy to create a PR if you’d prefer that over #188

**Comment by zpao** [comment]
The other PR is going to need to be updated a bunch anyway so feel free to make a new one. Like I said though, splitting the components is easy enough. The tooling right now blows up generating the TS declaration once you split and that's the bigger effort.

**Comment by kachkaev** [comment]
Looks like we can get away with something even simpler: #352. Typescript tooling and file splitting can be done later (much later TBH).

**Comment by kachkaev** [comment]
N.B. `qrcode.react@4` does not work in [satori](https://github.com/vercel/satori) which I used as an example in this feature request. See details in https://github.com/vercel/satori/issues/600. ‘Standard’ React server components (outside satori) render with no issues, but if you do want to use `qrcode.react` in OG images, you can downgrade to `qrcode.react@3.2.0` for now. Previous major version does not have `forwardRef` and `useMemo` which satori struggles with.
