### ISSUE TITLE
Supports for click events and non square icons

### ISSUE THREAD

**Issue by kecanwen** [zpao/qrcode.react#348]
Supports for click events and non square icons

**Comment by zpao** [comment]
#124 exists for tracking different shapes for the modules and #110 for round embedded images.

**Comment by zpao** [comment]
I haven't tested clicks in v3.x but just tested `trunk` and `onClick` is working fine for both canvas and svg. Should be working the same in v3 since we just pass all props through.

Let me know if I've misinterpreted and we can reopen.
