### ISSUE TITLE
[BUG] Not show the correct value

### ISSUE THREAD

**Issue by GabrielFMPinheiro** [zpao/qrcode.react#349]
When I use a value like this "d2d2dw*63040711" in value prop, the qr code only identifies this part: 63040711.

**Comment by zpao** [comment]
When I test this, the data is being read out correctly as the full string. Some tools (including iOS's built in scanner) do seem to attempt to parse things out and in this case are seeing the series of numbers as a phone number and present that without the rest.

AFAIK there's no formal standard here for what readers can do with the value.

**Comment by GabrielFMPinheiro** [comment]
Ok @zpao, I think you are right! I am new with qrcodes
I tested with android and some apps on iphone and they are working well, the problem seems to be with the iphone camera scan

**Comment by GabrielFMPinheiro** [comment]
Thanks for helping me
