### ISSUE TITLE
SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by phonglh-1050** [zpao/qrcode.react#359]
I'm setting up a QR component like this but when I click download I get this error. I've referred to the previous issue but it didn't work.
![image](https://github.com/user-attachments/assets/1c5854fc-9a92-4fc3-9570-e13c43e516f1)
This src part is the image url stored in aws S3

**Comment by zpao** [comment]
Duplicate of #143. v4 with support for `crossOrigin` (#324) hasn't shipped yet.
