### ISSUE TITLE
Image not included in download

### ISSUE THREAD

**Issue by justin-harr** [zpao/qrcode.react#379]
Browser: Chrome 
qrcode.react: 4.1.0

Code (relavent bits):
````
  const qrRef = useRef();

  const downloadSvg = async () => {
    const node = qrRef.current;
    if (node == null) {
      return;
    }

    const serializer = new XMLSerializer();
    const fileURI =
      "data:image/svg+xml;charset=utf-8," +
      encodeURIComponent(
        '<?xml version="1.0" standalone="no"?>' +
          serializer.serializeToString(node)
      );

    downloadStringAsFile(fileURI, "qrcode.svg");
  };
  
<QRCodeSVG
  ref={qrRef}
  value="hello world"
  size={1000}
  style={{ width: "100%", height: "100%" }}
  renderAs={"svg"}
  imageSettings={{
    src: logo,
    height:  250,
    width: 250,
    excavate: true,
  }}
/>
````

Application view:
<img width="442" alt="Screenshot 2024-10-29 at 8 50 00 PM" src="https://github.com/user-attachments/assets/1c7c013c-a2b9-40f8-be20-bf511bf277a5">

Result:
<img width="589" alt="Screenshot 2024-10-29 at 8 50 12 PM" src="https://github.com/user-attachments/assets/1b03b1f8-848d-45c6-af8e-722a9d3fd5b5">

Edit: It's a CORS issue. Can't delete the issue.

**Comment by limerence19** [comment]
is it solved? i have the same problem，version is 1.0.1
