### ISSUE TITLE
QRCode only displays the last value when iterated

### ISSUE THREAD

**Issue by wesharehoodies** [zpao/qrcode.react#44]
Let's say you have addresses 

`const  addresses = [1, 2, 3]`

And now if we Parent and we map the addresses to generate a list of QRs.

```
addresses.map(address => {
	return <AddressItem address={address} />
}
```

Inside the child `<AddressItem />`

We have something

```
const AddressItem = ({address}) => (
  <QRCode value={address} />
)
```
The QR would generate a QR from the last value (3 in this case)

Any propositions how we could solve this?

**Comment by zpao** [comment]
Trying to repro locally - it looks like it's only a problem when using numbers. Passing strings works as expected. I'm not typechecking and the underlying library doesn't either. So what you're seeing is actually the empty string encoded, not actually `3`.

I'm going to close out, but maybe I missed what's actually happening for you. Please provide runnable example code if that's the case (with something like https://codesandbox.io or https://glitch.com/)

**Comment by wesharehoodies** [comment]
I produced a simple example:

https://codesandbox.io/s/23n78zrjvy

Install the bread wallet app: https://itunes.apple.com/us/app/bread-bitcoin-wallet/id885251393?mt=8

Scan the QR codes. They all result giving the first QR address only.

**Comment by zpao** [comment]
Looks like it didn't save - that sandbox is broken and doesn't have any qrs.

**Comment by wesharehoodies** [comment]
Sorry about that-- will this one work?

https://codesandbox.io/s/23n78zrjvy

Actually, I downloaded a QR tester app and everything works. Seems like the bread wallet might have some anomaly.

**Comment by wesharehoodies** [comment]
Yes, the QR is working perfectly. Sorry for the trouble, thanks for taking the time!

**Comment by YanaKopyshchyk** [comment]
@wesharehoodies Hi! How did you solve the problem? I have the same
