### ISSUE TITLE
renderAs = "svg" is not working

### ISSUE THREAD

**Issue by Kiura** [zpao/qrcode.react#45]
renderAs = "svg" is not working and there's no documentation even though the feature is implemented. 

Also, is there a way to make rounded qrcode like here: [demo](https://larsjung.de/kjua/latest/demo/)

**Comment by zpao** [comment]
I haven't published a version to npm that contains the SVG code yet. And I have no intention of supporting stylized module rendering (like rounded corners in that tool).

**Comment by Kiura** [comment]
Do you have any plans to publish the svg version and when?
