### ISSUE TITLE
Create QR Code with border

### ISSUE THREAD

**Issue by AttitudeL** [zpao/qrcode.react#48]
Hi,
Thank you so much for this great work generating QR code. I have recently encountered an issue that if my client downloads the generated QR code and placed it on top of a complete black background, then QR scan will fail since the QR code does not have white border and thus merges with the black background.

Would there be an easy way to add a thin white border around the generated QR code?

Thanks in advance!

**Comment by zpao** [comment]
So the QRCode spec actually requires a margin of 4 (IIRC) modules around using the background color. I know you closed this, but it would actually be a good thing to be able to opt into. Of course, this is the DOM so you can always wrap in more nodes, include padding/margin, and call it a day, but for people using the `<canvas>` renderer and saving the image to disk, it's particularly useful.

I probably won't get to this but if somebody is interested in working on it, let me know.

**Comment by seanyesmunt** [comment]
I'm planning on working on this. @zpao anything specifically you had in mind?

**Comment by zpao** [comment]
Probably good to have a new boolean prop, `includeMargin` or something like that, and default to `false` so it's non-breaking. It'll make the logic more complicated - probably easiest to just update the data we get back from qr.js to include the margin module and then the renderers should adjust accordingly. It's possible qr.js has an option to include those without us needing to do any work, in which case it might be quick work.

**Comment by seanyesmunt** [comment]
Sorry for the long delay. I spent some time on this but didn't make any substantial progress. I need to spend some more time learning about canvas/svg. I hope to come back to this again when I get some free time if it's still open.
