### ISSUE TITLE
Feature Request: Support custom template

### ISSUE THREAD

**Issue by alieslamifard** [zpao/qrcode.react#51]
Hi,
i need to combine an image as template with qr-code.
i can create a canvas an draw two image in it, but do you have a better ideas a new feature?

**Comment by zpao** [comment]
Could you clarify a little bit? Are you trying to draw the QR onto another image or add an image to the QR Code? For the former, doubt anything will happen there. We may add a callback for the canvas renderer to get the QRCode image data out post-render. For the latter, see #50.
