### ISSUE TITLE
Qrcode not working

### ISSUE THREAD

**Issue by jurjees23** [zpao/qrcode.react#57]
Hi,
 Qrcode not working after build but working in development.

**Comment by zpao** [comment]
Do you have a reproducible test case?

**Comment by tomonari-t** [comment]
I got the problem that the QR Code is not showed at only `MSEdge@42.17134.x`

**Comment by yassh** [comment]
ping @zpao

**Comment by zpao** [comment]
The fix for this shipped in v0.9.3 in February.
