### ISSUE TITLE
Qrcode not working on ios google authenticator 2 

### ISSUE THREAD

**Issue by sleko** [zpao/qrcode.react#58]

**Comment by zpao** [comment]
Can you provide any more details? What does it mean to not work? What value are you encoding that is not being decoded properly?

**Comment by sleko** [comment]
The issue was in value QrCode, i have had "white space" in the name of the qrcode.
Issue is fixed by removing "white space"
This issue is not appeared on android.

**Comment by dashuser33** [comment]
@sleko does it mean you can close this issue or you think it still needs a fix?
