### ISSUE TITLE
PureRenderMixin

### ISSUE THREAD

**Issue by dcousens** [zpao/qrcode.react#6]
Could this component ~~be~~ use a [PureRenderMixin](https://facebook.github.io/react/docs/pure-render-mixin.html)?

**Comment by zpao** [comment]
No need to use PureRenderMixin but will add a custom `shouldComponentUpdate`.

**Comment by dcousens** [comment]
Thanks @zpao ,   was there any reason not to use `PureRenderMixin`?  My understanding was that was canonical?

**Comment by zpao** [comment]
This is shorter and doesn't have any dependencies, which means I can be a bit more flexible on dependencies (which is handy as we split things into more packages). It's slightly different from PureRenderMixin (no hasOwnProperty check, doesn't check length === first).

**Comment by dcousens** [comment]
Would it be worth making this into a `pure` function eventually to signify the lack of state?

**Comment by zpao** [comment]
The component itself isn't really pure since we're doing manual DOM operations.
