### ISSUE TITLE
Unknown Prop Warning for 'includeMargin'

### ISSUE THREAD

**Issue by NikolaDojic** [zpao/qrcode.react#67]
everything works fine, but it would be nice to get rid of this annoying warning.

`Warning: React does not recognize the 'includeMargin' prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `includemargin` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by adln** [comment]
+1

**Comment by zerocsss** [comment]
+1

**Comment by Ke100n4ik** [comment]
+1

**Comment by Ke100n4ik** [comment]
npm install qrcode.react@^0.7.2 works fine

**Comment by zpao** [comment]
Thanks for reporting. I just published 0.9.1 with the fix.
