### ISSUE TITLE
includeMargin bug with canvas renderer

### ISSUE THREAD

**Issue by anthonyringoet** [zpao/qrcode.react#68]
The newly added `includeMargin` feature is working for the SVG renderer but is not centering the qr code contents with the canvas renderer. This can be reproduced using the [project demo page](http://zpao.github.io/qrcode.react/)

## SVG renderer
![image](https://user-images.githubusercontent.com/576905/50629593-7ca32880-0f3d-11e9-80b1-929ebfd35fcb.png)

## Canvas renderer
![image](https://user-images.githubusercontent.com/576905/50629618-93497f80-0f3d-11e9-8d7e-438357aa4d58.png)

**Comment by zpao** [comment]
Bah, this is what I get for refactoring after I got it working. Thanks for the descriptive bug report. Fix and new release shortly.

**Comment by anthonyringoet** [comment]
Can confirm it's working in the 0.9.2 release, thank you!
