### ISSUE TITLE
How to use this qrcode 

### ISSUE THREAD

**Issue by ikram89** [zpao/qrcode.react#73]
how to use this qrcode and implement in my real code...

below my current code i try to implement but nothing happen:-

```
import ReactDOM from 'react-dom';

const React = require('react');
const QRCode = require('qrcode.react');

ReactDOM.render(<QRCode value="http://facebook.github.io/react/" />, mountNode);

```

**Comment by zpao** [comment]
It's going to be super tough to help without more code. From what I can see you don't have a `mountNode` specified, so I'd start there, and I'd look at the error console. There isn't enough here to work with so I'm going to close, but if you can repro in site like https://codesandbox.io/, please reopen.
