### ISSUE TITLE
qrcode.react 生成的二维码是永久的吗

### ISSUE THREAD

**Issue by wangyapeng** [zpao/qrcode.react#78]

**Comment by long-zhuge** [comment]
应该是永久的，我很久之前生成的二维码，现在还能打开。除非内容失效了。

**Comment by evagy** [comment]
二维码对应的只是一个字符串而已，解析规则不变，对应的字符串也不变。

**Comment by zpao** [comment]
What others said - with stable input (same options, like error level) the generated QR Code will be the same.
