### ISSUE TITLE
Typescript props define don't support `className` & `style`

### ISSUE THREAD

**Issue by TomIsion** [zpao/qrcode.react#84]
``` typescript
declare namespace qrcode {
	interface QRCodeProps {
		value: string;
		size?: number;
		bgColor?: string;
		fgColor?: string;
		level?: "L"|"M"|"Q"|"H";
		renderAs?: "svg" | "canvas";
	}

	type QRCode = React.ComponentClass<QRCodeProps>;
}

declare const qrcode: qrcode.QRCode;
export = qrcode;
```

From the README, `<QRCode />` support `className` & `style` to define ui format.

Please perfect the typescript define.

**Comment by zpao** [comment]
I don't manage the TS definitions, those are in DefinitelyTyped. You can send a PR there if you need them updated. https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/qrcode.react/index.d.ts
