### ISSUE TITLE
Convert qr code in base64

### ISSUE THREAD

**Issue by Angelk90** [zpao/qrcode.react#85]
Hi @zpao , would it be possible to create a function that as a return value converts the image to base64?
`QRCode.base64("text);`

**Comment by zilahir** [comment]
@Angelk90  that's pretty easy to do, i solved it like this: 

`const qrCodeCanvas = document.querySelectorAll("#qr-code-container canvas")[0]
    const canvasDataUrl = qrCodeCanvas.toDataURL('image/png')`

**Comment by Angelk90** [comment]
@zilahir : The problem that I don't have a single qr but a more specific list is a table I'm using: `react-data-table-component`

Here is an example: https://codesandbox.io/s/react-data-table-sandbox-h76se

When you click on the qr code the qr function is called, I would like the function to print the result.

**Comment by zilahir** [comment]
@Angelk90 i have forked your `sandbox` and implemented a possible [solution](https://codesandbox.io/s/react-data-table-sandbox-1e0ep?fontsize=14)

**Comment by Angelk90** [comment]
@zilahir : 
Thank you, but they just asked me to change some things for work.
I have to create a pdf where in this pdf I have to put some information and the qr code.
But the pdf must be created when you click not on the qr code but on a button.

Here is an example: https://codesandbox.io/s/react-data-table-sandbox-wc7vv

Can you give me some advice?

**Comment by zilahir** [comment]
@Angelk90  maybe like [this](https://codesandbox.io/embed/react-data-table-sandbox-rypn5?fontsize=14)

**Comment by Angelk90** [comment]
@zilahir :  Thank you, it seems to work properly.  May I ask that I have never used this attribute thing, if the table item is deleted does the link still remain or does it analyze the page every time?

**Comment by iCHAIT** [comment]
Hi @zilahir 

I am trying to do something similar to what @Angelk90 is doing but could not make it work from my case.

I want to render a QR code generated on the flyto a PDF. For generating pdf I am using [`react-pdf/renderer`](https://www.npmjs.com/package/@react-pdf/renderer).

Here is my code - 

```javascript
import React from "react";
import {Page, Text, View, Document, StyleSheet, Image} from "@react-pdf/renderer";
import QRCode from "qrcode.react";

export function PdfDocument(props) {
    return (
        <Document>
        <Page size="A4">    
          <View>
            <Text>Section #1</Text>
          </View>
          <View>
            <Text>Section #2</Text>
            <QRCode value="Hello" />
            
          </View>
        </Page>
      </Document>
    );
}
```

But I am getting the following error - 

`Error: Invalid element of type canvas passed to PDF renderer`


From what I understand I think I need to convert the QR code to a `png` or `jpeg` before rendering it to a pdf. But I am not sure how to do it? 

Can you please help me? How I can accomplish this?

**Comment by kievmontana** [comment]
@iCHAIT 
Convert the QR code first and pass it to your component as a prop.

Parent component:
`const qrCodeCanvas = document.querySelector('canvas');
const qrCodeDataUri = qrCodeCanvas.toDataURL('image/jpg', 0.3);`

Pass `qrCodeDataUri` as a prop to PDFDocument in Image source:
`<Image source={ {uri: props.image} } />`

**Comment by lixuanzaaa** [comment]
Hello there. Would it be possible to explain how the passing of props would work for this case?

**Comment by cchavezmx** [comment]
https://codesandbox.io/s/boring-hypatia-fcc8ep?file=/src/App.js

**Comment by JMRodriguez-work** [comment]
Sandbox not found :(
