### ISSUE TITLE
Is it possible to Download QR code without displaying the preview.

### ISSUE THREAD

**Issue by srinivasyl** [zpao/qrcode.react#89]
Onclick of button QR code should be downloaded.
```
downloadQR = (QRdata) => {
let data = QRdata
        let qr = (<QRCode
            id={data._id+'QR'}
            value={JSON.stringify({data})}
            size={300}
            level={"H"}
            includeMargin={true}
        />)
        console.log(qr)
}
```
I want `qr` to be downloaded as image `qr` is object containing size, color, render as etc.
Is there a way to do this?

**Comment by ctq123** [comment]
同问 +1

**Comment by zpao** [comment]
This isn't a case I intend to support. If you want you can render to a container that isn't displayed. Or just use another library.
