### ISSUE TITLE
Add images inside the qr code

### ISSUE THREAD

**Issue by bitttttten** [zpao/qrcode.react#96]
I am attempting to generate QR codes with a cut out in the middle so I can place an image inside. Something along the lines of:

<img src="https://user-images.githubusercontent.com/19930241/70221887-6bfcc300-1749-11ea-93ce-33cc4f9a1f20.png" width="100" height="100" />

Maybe this is a feature request, but more of an investigation. Is it possible to do something like this with this library?

**Comment by zpao** [comment]
Yes as of 1.0. Check the imageSettings prop: https://github.com/zpao/qrcode.react/blob/master/README.md#available-props
