### ISSUE TITLE
How can I render QR Code on a PDF?

### ISSUE THREAD

**Issue by iCHAIT** [zpao/qrcode.react#98]
HI, 

I want to render a QR code generated on the fly to a PDF. For generating pdf I am using [`react-pdf/renderer`](https://www.npmjs.com/package/@react-pdf/renderer).

Here is my code -

```javascript
import React from "react";
import {Page, Text, View, Document, StyleSheet, Image} from "@react-pdf/renderer";
import QRCode from "qrcode.react";

export function PdfDocument(props) {
    return (
        <Document>
        <Page size="A4">    
          <View>
            <Text>Section #1</Text>
          </View>
          <View>
            <Text>Section #2</Text>
            <QRCode value="Hello" />
            
          </View>
        </Page>
      </Document>
    );
}
```

But I am getting the following error -

`Error: Invalid element of type canvas passed to PDF renderer`

From what I understand I think I need to convert the QR code to a png or jpeg before rendering it to a pdf. But I am not sure how to do it?

Can you please help me? How I can accomplish this?

**Comment by gino8080** [comment]
i need the same

**Comment by zpao** [comment]
I'm not planning on supporting alternate renderers. If you'd like to generate a data blob then you'll probably want to use the underlying qrcode library directly.
